/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'on-tertiary-container': '#91131e',
        'surface-variant': '#e2e2e2',
        'tertiary-fixed-dim': '#ffb3af',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdad7',
        'tertiary-container': '#ff9e9a',
        'secondary-fixed': '#d5e5ed',
        'inverse-primary': '#4fd5ff',
        'surface-container-high': '#e8e8e8',
        'on-background': '#1a1c1c',
        'surface-container': '#eeeeee',
        'on-primary-container': '#005063',
        tertiary: '#b02c31',
        'secondary-container': '#d5e5ed',
        'on-secondary-fixed': '#0f1e23',
        'secondary-fixed-dim': '#b9c9d1',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#3a494f',
        'primary-fixed-dim': '#4fd5ff',
        'outline-variant': '#bbc9cf',
        'on-primary-fixed': '#001f28',
        surface: '#f9f9f9',
        'surface-tint': '#006780',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#410005',
        background: '#f9f9f9',
        'primary-container': '#03c8f5',
        'surface-container-highest': '#e2e2e2',
        secondary: '#526167',
        'surface-dim': '#dadada',
        'surface-container-low': '#f3f3f4',
        'on-surface': '#1a1c1c',
        'on-secondary-container': '#58676e',
        'primary-fixed': '#b7eaff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2f3131',
        outline: '#6c797f',
        'on-primary-fixed-variant': '#004e61',
        'on-error': '#ffffff',
        'surface-bright': '#f9f9f9',
        error: '#ba1a1a',
        'on-surface-variant': '#3c494e',
        'inverse-on-surface': '#f0f1f1',
        'on-tertiary': '#ffffff',
        primary: '#006780',
        'on-tertiary-fixed-variant': '#8e101d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1rem',
        margin: '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'mono-data': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      keyframes: {
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-3px)' },
        },
      },
      animation: {
        'bounce-subtle': 'bounce-subtle 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
